CREATE TABLE "EMPLOYEE"
(
  EMPLOYEE_ID NUMBER PRIMARY KEY,
  EMP_FIRSTNAME VARCHAR2(100),
  EMP_LASTNAME VARCHAR2(100),
  DEPARTMENT_ID NUMBER,
  SALARY NUMBER,
  EMP_EMAIL VARCHAR2(100)
);


CREATE TABLE "DEPARTMENT"
(
  DEPARTMENT_ID NUMBER PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(100)
);

--SEQUENCE AND TRIGGER FOR EMPLOYEE PK
CREATE SEQUENCE SQ_EMP_PK
START WITH 3
INCREMENT BY 7;

CREATE OR REPLACE TRIGGER TR_INSERT_EMP
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
  SELECT SQ_EMP_PK.NEXTVAL INTO :new.EMPLOYEE_ID FROM DUAL;
END;


--SEQUENCE AND TRIGGER FOR DEPARTMENT PK
CREATE SEQUENCE SQ_DEP_PK
START WITH 2
INCREMENT BY 13;

CREATE OR REPLACE TRIGGER TR_INSERT_DEP
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
  SELECT SQ_DEP_PK.NEXTVAL INTO :new.DEPARTMENT_ID FROM DUAL;
END;

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES ('ACCOUNTING');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('IT SERVICES');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('ORDERS');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('PAUL', 'NELSON',2, 50000, 'PaulCNelson@armyspy.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('JOHNNIE', 'AMAR',15, 70000, 'JohnnieCAmar@armyspy.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('MARY', 'MAURICE',15, 90000, 'MaryIMaurice@rhyta.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('MARIO', 'WRIGHT',28, 40000, 'MarioLWright@jourrapide.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('RICHARD', 'HAMMOND',28, 50000, 'RichardSHammond@teleworm.us');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('MMICHAEL', 'WHITE',28, 50000, 'MichaelKWhite@rhyta.com');



SELECT * FROM EMPLOYEE WHERE DEPARTMENT_ID = 2;



UPDATE EMPLOYEE SET SALARY = SALARY*1.10 WHERE SALARY = 50000;


CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE (DEPT_ID IN NUMBER, NEW_AVG_SAL OUT NUMBER, VALID_ID OUT VARCHAR2)
IS
BEGIN
    UPDATE EMPLOYEE 
    SET SALARY = SALARY*1.10 
    WHERE DEPARTMENT_ID = DEPT_ID;
    
    SELECT AVG(SALARY) INTO NEW_AVG_SAL FROM EMPLOYEE;
    
    IF(1 = 1)THEN
    VALID_ID := '0';
    
    ELSE
    VALID_ID := '1';
    END IF;
END;

