CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER NOT NULL,
EMP_FIRSTNAME VARCHAR2(1000),
EMP_LASTNAME VARCHAR2(1000),
DEPARTMENT_ID INTEGER  NOT NULL,
SALARY INTEGER,
EMP_EMAIL VARCHAR2(2000)

);

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER NOT NULL,
DEPARTMENT_NAME VARCHAR2(1000)
);

CREATE SEQUENCE SQ_EMPLOYEE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
  SELECT SQ_EMPLOYEE.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM EMPLOYEE;
    --DUAL IS A DUMMY TABLE. USE IT WHEN YOU DON'T REQUIRE A TABLE
    --BUT NEED TABLE-LIKE SYNTAX. 
END;

CREATE SEQUENCE SQ_DEPARTMENT
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_INSERT_DEPARTMENT
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
  SELECT SQ_DEPARTMENT.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DEPARTMENT;
END;

DROP TABLE DEPARTMENT;

INSERT INTO EMPLOYEE (EMPLOYEE_ID,EMP_FIRSTNAME, EMP_LASTNAME,DEPARTMENT_ID,
SALARY,EMP_EMAIL) 
VALUES (2,'SARAH','JOHNSON',1,40000,'SARAH@GMAIL.COM');

SELECT * FROM EMPLOYEE;


