CREATE TABLE "BEAR"(
BEAR_ID INTEGER PRIMARY KEY,
BEAR_NAME VARCHAR2(2000),

BEAR_AGE INTEGER,
CONSTRAINT CHECK_BEAR_AGE 
CHECK (BEAR_AGE > 0),

BEAR_WEIGHT INTEGER,
CONSTRAINT CHECK_BEAR_WEIGHT
CHECK (BEAR_WEIGHT > 0),

CAVE_ID INTEGER,
BEAR_TYPE_ID INTEGER,
FOREIGN KEY(BEAR_TYPE_ID) REFERENCES BEAR_TYPE(BEAR_TYPE_ID),
FOREIGN KEY(CAVE_ID) REFERENCES CAVE(CAVE_ID)
);

CREATE TABLE "BEAR_TYPE"(
BEAR_TYPE INTEGER PRIMARY KEY,
BEAR_TYPE_NAME VARCHAR2(2000)
)

CREATE TABLE "CAVE"(
CAVE_ID INTEGER PRIMARY KEY,
CAVE_NAME VARCHAR2(100)
CONSTRAINT CHECK_CAVE_NAME UNIQUE,
MAX_BEARS INTEGER DEFAULT (4)
)

CREATE TABLE "BEAR_BEEHIVE"(
BEAR_ID INTEGER, 
FOREIGN KEY(BEAR_ID)
REFERENCES BEAR(BEAR_ID),

BEEHIVE_ID INTEGER,
FOREIGN KEY (BEEHIVE_ID)
REFERENCES BEEHIVE(BEEHIVE_ID),

CONSTRAINT BEAR_BEEHIVE_ID PRIMARY KEY (BEAR_ID, BEEHIVE_ID)
)

CREATE TABLE "BEEHIVE"(
BEEHIVE_ID INTEGER PRIMARY KEY,
HIVE_WEIGHT INTEGER DEFAULT 50,
CONSTRAINT CHECK_HIVE_WEIGHT
CHECK (HIVE_WEIGHT > 0)
)