CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID INTEGER PRIMARY KEY,
EMP_FIRSTNAME VARCHAR2(2000),
EMP_LASTNAME VARCHAR2(200),
DEPARTMENT_ID INTEGER,
SALARY NUMBER,
EMP_EMAIL VARCHAR2(2000)

)

CREATE TABLE DEPARTMENT(

DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(2000)

);

CREATE SEQUENCE EMP_INC
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EMP_TR
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
SELECT EMP_INC.NEXTVAL INTO :new.EMPLOYEE_ID FROM DUAL;
END;


CREATE SEQUENCE DEP_INC
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER DEP_TR
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
SELECT DEP_INC.NEXTVAL INTO :new.DEPARTMENT_ID FROM DUAL;
END;


INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES('DEPARTMENT A');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES('DEPARTMENT B');
INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES('DEPARTMENT C');

INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('JOHN','KENT',1,20.5,'KENTJ@DEPARTMENT.NET');
INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('SALEH','ALOBAID',1,20.5,'ALOBAIDS@DEPARTMENT.NET');
INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('LOGAN','MCCARTHY',2,20.5,'MCCARTHYL@DEPARTMENT.NET');
INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('ZACH','GILLESPIE',2,20.5,'GILLESPIEZ@DEPARTMENT.NET');
INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('ERIC','SAUNDERS',3,20.5,'SAUNDERSE@DEPARTMENT.NET');
INSERT INTO EMPLOYEE(EMP_FIRSTNAME,EMP_LASTNAME,DEPARTMENT_ID,SALARY,EMP_EMAIL) VALUES('ALEX','POTWARDOWSKI',3,20.5,'POTWARDOWSKIA@DEPARTMENT.NET');


CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE(ID IN INTEGER,PERCENTAGE IN INTEGER,AVG_SALARY OUT SYS_REFCURSOR,VALID OUT BOOLEAN)

AS

BEGIN
VALID:=FALSE;
UPDATE EMPLOYEE SET SALARY=(SALARY+SALARY*(1/PERCENTAGE)) WHERE EMPLOYEE_ID=ID;
OPEN AVG_SALARY FOR
SELECT AVG(SALARY) FROM EMPLOYEE;
VALID:=TRUE;
END;

