--------------------------------------------------------
--  File created - Monday-April-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "EERIC5"."BANK_ACCOUNT" 
   (	"BANK_ACCOUNT_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"BANK_ACCOUNT_NAME" VARCHAR2(25 BYTE), 
	"BALANCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_USER
--------------------------------------------------------

  CREATE TABLE "EERIC5"."BANK_USER" 
   (	"BANK_USER_ID" NUMBER(*,0), 
	"BANK_USERNAME" VARCHAR2(25 BYTE), 
	"BANK_PASSWORD" VARCHAR2(25 BYTE), 
	"USER_SUPER_STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SQ_BANK_ACCOUNT_PK
--------------------------------------------------------

   CREATE SEQUENCE  "EERIC5"."SQ_BANK_ACCOUNT_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_DEPART_PK
--------------------------------------------------------

   CREATE SEQUENCE  "EERIC5"."SQ_DEPART_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_EMP_PK
--------------------------------------------------------

   CREATE SEQUENCE  "EERIC5"."SQ_EMP_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_USER_PK
--------------------------------------------------------

   CREATE SEQUENCE  "EERIC5"."SQ_USER_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into EERIC5.BANK_ACCOUNT
SET DEFINE OFF;
Insert into EERIC5.BANK_ACCOUNT (BANK_ACCOUNT_ID,USER_ID,BANK_ACCOUNT_NAME,BALANCE) values (42,45,'Checking',0);
Insert into EERIC5.BANK_ACCOUNT (BANK_ACCOUNT_ID,USER_ID,BANK_ACCOUNT_NAME,BALANCE) values (23,1,'Checking_01',1400);
Insert into EERIC5.BANK_ACCOUNT (BANK_ACCOUNT_ID,USER_ID,BANK_ACCOUNT_NAME,BALANCE) values (24,1,'Savings',11100);
REM INSERTING into EERIC5.BANK_USER
SET DEFINE OFF;
Insert into EERIC5.BANK_USER (BANK_USER_ID,BANK_USERNAME,BANK_PASSWORD,USER_SUPER_STATUS) values (1,'temp','temp','y');
Insert into EERIC5.BANK_USER (BANK_USER_ID,BANK_USERNAME,BANK_PASSWORD,USER_SUPER_STATUS) values (45,'Eric','Biehl','n');
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_BANK_ACCOUNT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "EERIC5"."TR_INSERT_BANK_ACCOUNT" 
BEFORE INSERT ON BANK_ACCOUNT
FOR EACH ROW 
BEGIN
  SELECT SQ_BANK_ACCOUNT_PK.NEXTVAL INTO :NEW.BANK_ACCOUNT_ID FROM DUAL;
END;
/
ALTER TRIGGER "EERIC5"."TR_INSERT_BANK_ACCOUNT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_USER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "EERIC5"."TR_INSERT_USER" 
BEFORE INSERT ON BANK_USER
FOR EACH ROW 
BEGIN
  SELECT SQ_USER_PK.NEXTVAL INTO :NEW.BANK_USER_ID FROM DUAL;
END;
/
ALTER TRIGGER "EERIC5"."TR_INSERT_USER" ENABLE;
--------------------------------------------------------
--  DDL for Procedure GETUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EERIC5"."GETUSER" (USERID IN NUMBER, USERNAME OUT VARCHAR) AS BEGIN SELECT BANK_USERdNAME INTO USERNAME FROM BANK_USER WHERE USERID = BANK_USER_ID; END

/
--------------------------------------------------------
--  DDL for Procedure SP_GIVE_RAISE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EERIC5"."SP_GIVE_RAISE" 
(DEPARTMENT_ID IN INTEGER, NEWAMOUNT OUT INTEGER, ISVALID OUT VARCHAR2)
IS
RETURN NEWAMOUNT;

  NEWAMOUNT INTEGER;
  ISVALID VARCHAR2(1);

BEGIN
  SELECT INTO NEWAMOUNT FROM DEPARTMENT WHERE DEPARTMENT_ID = DPARTMENT.DEPARTMENT_ID;
  NEWAMOUNT := NEWAMOUNT * 1.1;
  
  IF DEPARTMENT_ID > 0 AND DEPARTMENT < 5 THEN
    ISVALID := 'Y';
  ELSE
    ISVALID := 'N';
  END IF;
END;

/
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "EERIC5"."BANK_ACCOUNT" ADD CONSTRAINT "OVERDRAFT_CHECK" CHECK (BALANCE > -1) ENABLE;
  ALTER TABLE "EERIC5"."BANK_ACCOUNT" ADD PRIMARY KEY ("BANK_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BANK_USER
--------------------------------------------------------

  ALTER TABLE "EERIC5"."BANK_USER" ADD PRIMARY KEY ("BANK_USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "EERIC5"."BANK_ACCOUNT" ADD CONSTRAINT "USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "EERIC5"."BANK_USER" ("BANK_USER_ID") ENABLE;
