CREATE TABLE ERS_REIMBURSEMENTS(
  R_ID          NUMBER NOT NULL,
  R_AMOUNT      NUMBER NOT NULL, 
  R_DESCR       VARCHAR2(100),
  R_RECEIPT     BLOB, 
  R_SUBMITTED   TIMESTAMP NOT NULL,
  R_RESOLVED    TIMESTAMP, 
  U_ID_AUTHOR   NUMBER NOT NULL,
  U_ID_RESOLVER NUMBER,
  RT_TYPE       NUMBER NOT NULL,
  RT_STATUS     NUMBER NOT NULL,
  CONSTRAINT    PK_ERS_REIMBURSEMENTS PRIMARY KEY  (R_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
  RS_ID         NUMBER NOT NULL,
  RS_STATUS     VARCHAR2(30) NOT NULL,
  CONSTRAINT    PK_ERS_REIMBURSEMENT_STATUS PRIMARY KEY (RS_ID)
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE (
  RT_ID         NUMBER NOT NULL,
  RT_TYPE       VARCHAR2(30) NOT NULL,
  CONSTRAINT    PK_ERS_REIMBURSEMENT_TYPE PRIMARY KEY (RT_ID)
);

CREATE TABLE ERS_USER_ROLES(
  UR_ID         NUMBER NOT NULL,
  UR_ROLE       VARCHAR2(40),
  CONSTRAINT    PK_ERS_USER_ROLES PRIMARY KEY (UR_ID)
);

CREATE TABLE ERS_USERS(
  U_ID          NUMBER NOT NULL,
  U_USERNAME    VARCHAR2(40) UNIQUE NOT NULL,
  U_PASSWORD    VARCHAR2(40) NOT NULL,
  U_FIRSTNAME   VARCHAR2(30),
  U_LASTNAME    VARCHAR2(30),
  U_EMAIL       VARCHAR2(100) UNIQUE,
  UR_ID         NUMBER
);