CREATE TABLE "BANK_USER"
(
  USER_ID NUMBER,
  USERNAME VARCHAR2(50),
  USER_PW VARCHAR2(50),
  FIRSTNAME VARCHAR2(100),
  LASTNAME VARCHAR2(100)
);

ALTER TABLE BANK_USER
ADD CONSTRAINT USER_PK
    PRIMARY KEY(USER_ID);
    
ALTER TABLE BANK_USER
ADD FIRSTNAME VARCHAR2(100);

ALTER TABLE BANK_USER
ADD LASTNAME VARCHAR2(100);

ALTER TABLE BANK_ACCOUNT
ADD ACCOUNT_NAME VARCHAR2(100);

CREATE TABLE "BANK_ACCOUNT"
(
  BANK_ACCOUNT_ID NUMBER PRIMARY KEY,
  BALANCE NUMBER
);

CREATE TABLE "USER_BANK_ACCOUNT"
(
  BANK_ACCOUNT_ID NUMBER,
  USER_ID NUMBER
);

ALTER TABLE USER_BANK_ACCOUNT
ADD CONSTRAINT USER_BANK_ACC_PK
  PRIMARY KEY(BANK_ACCOUNT_ID, USER_ID);
  
ALTER TABLE USER_BANK_ACCOUNT
ADD CONSTRAINT USER_BANK_ACC_FK1
    FOREIGN KEY(BANK_ACCOUNT_ID) REFERENCES BANK_ACCOUNT(BANK_ACCOUNT_ID);
    FOREIGN KEY(USER_ID) REFERENCES BANK_USER(USER_ID);

ALTER TABLE USER_BANK_ACCOUNT
ADD CONSTRAINT USER_BANK_ACC_FK2
    FOREIGN KEY(USER_ID) REFERENCES BANK_USER(USER_ID); 
  

INSERT INTO BANK_USER
(USER_ID, USERNAME, USER_PW, FIRSTNAME, LASTNAME)
VALUES
(7, 'MOMONEY', 'ChaChing', 'Warren', 'Buffett');


--CREATE SEQUENCE FOR BANK PRIMARY KEYS
CREATE SEQUENCE SQ_BANK_USER_PK
START WITH 11
INCREMENT BY 13;

--CREATE BEFORE INSERT TRIGGER FOR BANK_USER PRIMARY KEYS
CREATE OR REPLACE TRIGGER TR_INSERT_BANK_USER
BEFORE INSERT ON BANK_USER
FOR EACH ROW
BEGIN
  SELECT SQ_BANK_USER_PK.NEXTVAL INTO :new.USER_ID FROM DUAL;
END;

DELETE FROM BANK_ACCOUNT WHERE BANK_ACCOUNT_ID = 84;