--------------------------------------------------------
--  File created - Monday-April-17-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BANK_ACCOUNT" 
   (	"BANK_ACCOUNT_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"BANK_ACCOUNT_NAME" VARCHAR2(200 BYTE), 
	"BALANCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_LOGON
--------------------------------------------------------

  CREATE TABLE "ADMIN"."USER_LOGON" 
   (	"USER_ID" NUMBER(*,0), 
	"USER_NAME" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SQ_BANK_ACCOUNT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SQ_BANK_ACCOUNT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_USER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SQ_USER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into ADMIN.BANK_ACCOUNT
SET DEFINE OFF;
REM INSERTING into ADMIN.USER_LOGON
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_ACCOUNT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TR_INSERT_ACCOUNT" 
BEFORE INSERT ON BANK_ACCOUNT
FOR EACH ROW
BEGIN
  SELECT SQ_BANK_ACCOUNT_ID.NEXTVAL INTO :NEW.BANK_ACCOUNT_ID FROM DUAL;
    
END;
/
ALTER TRIGGER "ADMIN"."TR_INSERT_ACCOUNT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_USERS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TR_INSERT_USERS" 
BEFORE INSERT ON USER_LOGON
FOR EACH ROW
BEGIN
  SELECT SQ_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
  
END;
/
ALTER TRIGGER "ADMIN"."TR_INSERT_USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BANK_ACCOUNT" ADD PRIMARY KEY ("BANK_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_LOGON
--------------------------------------------------------

  ALTER TABLE "ADMIN"."USER_LOGON" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BANK_ACCOUNT" ADD CONSTRAINT "FK_BANK_ACCOUNT_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "ADMIN"."USER_LOGON" ("USER_ID") ENABLE;
