--------------------------------------------------------
--  File created - Wednesday-April-26-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENTS
--------------------------------------------------------

  CREATE TABLE "MASTER"."ERS_REIMBURSEMENTS" 
   (	"R_ID" NUMBER(*,0), 
	"R_AMMOUNT" NUMBER(22,2), 
	"R_DESCRIPTION" VARCHAR2(100 BYTE), 
	"R_RECEIPT" BLOB, 
	"R_SUBMMITTED" TIMESTAMP (6), 
	"R_RESOLVED" TIMESTAMP (6), 
	"U_ID_AUTHOR" NUMBER(*,0), 
	"U_ID_RESOLVER" NUMBER(*,0), 
	"RT_TYPE" NUMBER(*,0), 
	"RT_STATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("R_RECEIPT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT_STATUS
--------------------------------------------------------

  CREATE TABLE "MASTER"."ERS_REIMBURSEMENT_STATUS" 
   (	"RS_ID" NUMBER(*,0), 
	"RS_STATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "MASTER"."ERS_REIMBURSEMENT_TYPE" 
   (	"RT_ID" NUMBER(*,0), 
	"RT_TYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ERS_USERS
--------------------------------------------------------

  CREATE TABLE "MASTER"."ERS_USERS" 
   (	"U_ID" NUMBER(*,0), 
	"U_USERNAME" VARCHAR2(40 BYTE), 
	"U_PASSWORD" VARCHAR2(40 BYTE), 
	"U_FIRSTNAME" VARCHAR2(30 BYTE), 
	"U_LASTNAME" VARCHAR2(30 BYTE), 
	"U_EMAIL" VARCHAR2(100 BYTE), 
	"UR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ERS_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "MASTER"."ERS_USER_ROLES" 
   (	"UR_ID" NUMBER(*,0), 
	"UR_ROLE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SQ_ERS_USERS_PK
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."SQ_ERS_USERS_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_REIMBURSEMENTS_PK
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."SQ_REIMBURSEMENTS_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_REIMBURSEMENT_STATUS_PK
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."SQ_REIMBURSEMENT_STATUS_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_REIMBURSEMENT_TYPE_PK
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."SQ_REIMBURSEMENT_TYPE_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SQ_USER_ROLES_PK
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."SQ_USER_ROLES_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into MASTER.ERS_REIMBURSEMENTS
SET DEFINE OFF;
REM INSERTING into MASTER.ERS_REIMBURSEMENT_STATUS
SET DEFINE OFF;
REM INSERTING into MASTER.ERS_REIMBURSEMENT_TYPE
SET DEFINE OFF;
REM INSERTING into MASTER.ERS_USERS
SET DEFINE OFF;
REM INSERTING into MASTER.ERS_USER_ROLES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UQ_U_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTER"."UQ_U_EMAIL" ON "MASTER"."ERS_USERS" ("U_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_U_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTER"."UQ_U_USERNAME" ON "MASTER"."ERS_USERS" ("U_USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TR_REIMBURSEMENTS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."TR_REIMBURSEMENTS" 
BEFORE INSERT ON ERS_REIMBURSEMENTS
FOR EACH ROW
BEGIN
  SELECT SQ_REIMBURSEMENTS_PK.NEXTVAL INTO :NEW.R_ID FROM DUAL;
END;
/
ALTER TRIGGER "MASTER"."TR_REIMBURSEMENTS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_REIMBURSEMENT_STATUS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."TR_REIMBURSEMENT_STATUS" 
BEFORE INSERT ON ERS_REIMBURSEMENT_STATUS
FOR EACH ROW
BEGIN
  SELECT SQ_REIMBURSEMENT_STATUS_PK.NEXTVAL INTO :NEW.RS_ID FROM DUAL;
END;
/
ALTER TRIGGER "MASTER"."TR_REIMBURSEMENT_STATUS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_REIMBURSEMENT_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."TR_REIMBURSEMENT_TYPE" 
BEFORE INSERT ON ERS_REIMBURSEMENT_TYPE
FOR EACH ROW
BEGIN
  SELECT SQ_REIMBURSEMENT_TYPE_PK.NEXTVAL INTO :NEW.RT_ID FROM DUAL;
END;
/
ALTER TRIGGER "MASTER"."TR_REIMBURSEMENT_TYPE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_USER_ROLES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."TR_USER_ROLES" 
BEFORE INSERT ON ERS_USER_ROLES
FOR EACH ROW
BEGIN
  SELECT SQ_USER_ROLES_PK.NEXTVAL INTO :NEW.UR_ID FROM DUAL;
END;
/
ALTER TRIGGER "MASTER"."TR_USER_ROLES" ENABLE;
--------------------------------------------------------
--  DDL for Procedure UPD_USER_INFO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "MASTER"."UPD_USER_INFO" 
AS
BEGIN
UPDATE ERS_USERS 
SET  U_USERNAME=:new.U_USERNAME,
U_PASSWORD=:new.U_PASSWORD,
U_FIRSTNAME=:new.U_FIRSTNAME, 
U_LASTNAME=:new.U_LASTNAME,
USER_EMAIL=:new.USER_EMAIL
WHERE U_ID =:old.U_ID;
END;
show errors procedure <UPD_USER_INFO>;

/
--------------------------------------------------------
--  Constraints for Table ERS_USERS
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_USERS" ADD CONSTRAINT "UQ_U_EMAIL" UNIQUE ("U_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_USERS" ADD CONSTRAINT "UQ_U_USERNAME" UNIQUE ("U_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_USERS" ADD PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_USERS" MODIFY ("UR_ID" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_USERS" MODIFY ("U_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_USERS" MODIFY ("U_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_USERS" MODIFY ("U_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERS_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_USER_ROLES" ADD PRIMARY KEY ("UR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_USER_ROLES" MODIFY ("UR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_TYPE" ADD PRIMARY KEY ("RT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_TYPE" MODIFY ("RT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_TYPE" MODIFY ("RT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT_STATUS
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_STATUS" ADD PRIMARY KEY ("RS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_STATUS" MODIFY ("RS_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENT_STATUS" MODIFY ("RS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENTS
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" ADD PRIMARY KEY ("R_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("RT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("RT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("U_ID_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("R_SUBMMITTED" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("R_AMMOUNT" NOT NULL ENABLE);
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" MODIFY ("R_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ERS_REIMBURSEMENTS
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" ADD CONSTRAINT "FK_REIMBURSEMENTS_RESOLVER" FOREIGN KEY ("U_ID_RESOLVER")
	  REFERENCES "MASTER"."ERS_USERS" ("U_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" ADD CONSTRAINT "FK_REIMBURSEMENTS_RT_STATUS" FOREIGN KEY ("RT_STATUS")
	  REFERENCES "MASTER"."ERS_REIMBURSEMENT_STATUS" ("RS_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" ADD CONSTRAINT "FK_REIMBURSEMENTS_RT_TYPE" FOREIGN KEY ("RT_TYPE")
	  REFERENCES "MASTER"."ERS_REIMBURSEMENT_TYPE" ("RT_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MASTER"."ERS_REIMBURSEMENTS" ADD CONSTRAINT "FK_REIMBURSEMENTS_U_ID_AUTHOR" FOREIGN KEY ("U_ID_AUTHOR")
	  REFERENCES "MASTER"."ERS_USERS" ("U_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ERS_USERS
--------------------------------------------------------

  ALTER TABLE "MASTER"."ERS_USERS" ADD CONSTRAINT "FK_ERS_USERS_UR_ID" FOREIGN KEY ("UR_ID")
	  REFERENCES "MASTER"."ERS_USER_ROLES" ("UR_ID") ON DELETE CASCADE ENABLE;
