--------------------------------------------------------
--  File created - Tuesday-April-11-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANKACCOUNT
--------------------------------------------------------

  CREATE TABLE "MASTER"."BANKACCOUNT" 
   (	"ACCOUNTID" NUMBER, 
	"ACCOUNTNAME" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER, 
	"USERID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANKUSER
--------------------------------------------------------

  CREATE TABLE "MASTER"."BANKUSER" 
   (	"USERID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence BANK_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."BANK_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence USER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MASTER"."USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
REM INSERTING into MASTER.BANKACCOUNT
SET DEFINE OFF;
Insert into MASTER.BANKACCOUNT (ACCOUNTID,ACCOUNTNAME,BALANCE,USERID) values (4,'wellsfargo',5,5);
Insert into MASTER.BANKACCOUNT (ACCOUNTID,ACCOUNTNAME,BALANCE,USERID) values (9,'useraccount2',5,7);
REM INSERTING into MASTER.BANKUSER
SET DEFINE OFF;
Insert into MASTER.BANKUSER (USERID,USERNAME,PASSWORD) values (5,'gabe','password');
Insert into MASTER.BANKUSER (USERID,USERNAME,PASSWORD) values (7,'Zale','password');
--------------------------------------------------------
--  DDL for Index BANKACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTER"."BANKACCOUNT_PK" ON "MASTER"."BANKACCOUNT" ("ACCOUNTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANKUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MASTER"."BANKUSER_PK" ON "MASTER"."BANKUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger INCREMENT_BANK_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."INCREMENT_BANK_INSERT" 
before insert on BANKACCOUNT
for each row
begin
    select bank_id_seq.nextval into :new.accountid from dual;
end;
/
ALTER TRIGGER "MASTER"."INCREMENT_BANK_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENT_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "MASTER"."INCREMENT_INSERT" 
before insert on BANKUSER
for each row
begin
    select user_id_seq.nextval into : new.userid from dual;
end;
/
ALTER TRIGGER "MASTER"."INCREMENT_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table BANKUSER
--------------------------------------------------------

  ALTER TABLE "MASTER"."BANKUSER" ADD CONSTRAINT "BANKUSER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."BANKUSER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANKACCOUNT
--------------------------------------------------------

  ALTER TABLE "MASTER"."BANKACCOUNT" ADD CONSTRAINT "BANKACCOUNT_PK" PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MASTER"."BANKACCOUNT" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANKACCOUNT
--------------------------------------------------------

  ALTER TABLE "MASTER"."BANKACCOUNT" ADD CONSTRAINT "BANKACCOUNT_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "MASTER"."BANKUSER" ("USERID") ENABLE;
