CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER PRIMARY KEY,
EMP_FIRSTNAME VARCHAR2(250),
EMP_LASTNAME VARCHAR2(250),
DEPARTMENT_ID INTEGER,
SALARY INTEGER,
EMP_EMAIL VARCHAR(250)
)

CREATE TABLE DEPARTMENT(
DEPARTMENT_ID INTEGER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(250)
)

CREATE SEQUENCE SQ_EMP_PK
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_EMP
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW 
BEGIN
  SELECT SQ_EMP_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;

CREATE SEQUENCE SQ_DEPART_PK
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_DEPART
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW 
BEGIN
  SELECT SQ_DEPART_PK.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;

CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE
(DEPARTMENT_ID IN INTEGER, NEWAMOUNT OUT INTEGER, ISVALID OUT VARCHAR2)
IS
RETURN NEWAMOUNT;

  NEWAMOUNT INTEGER;
  ISVALID VARCHAR2(1);

BEGIN
  SELECT INTO NEWAMOUNT FROM DEPARTMENT WHERE DEPARTMENT_ID = DPARTMENT.DEPARTMENT_ID;
  NEWAMOUNT := NEWAMOUNT * 1.1;
  
  IF DEPARTMENT_ID > 0 AND DEPARTMENT < 5 THEN
    ISVALID := 'Y';
  ELSE
    ISVALID := 'N';
  END IF;
END;