CREATE TABLE BANK_ACCOUNT(
BANK_ACCOUNT_ID INTEGER NOT NULL,
USER_ID INTEGER NOT NULL,
BANK_ACCOUNT_NAME VARCHAR2(2000),
BALANCE INTEGER
);

CREATE TABLE USER_LOGON(
USER_ID INTEGER NOT NULL,
USER_NAME VARCHAR2(2000),
PASSWORD VARCHAR(2000)
);

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_BANK_ACCOUNT_USER_ID
FOREIGN KEY(USER_ID) REFERENCES USER_LOGON(USER_ID);

ALTER TABLE BANK_ACCOUNT DROP CONSTRAINT FK_BANK_ACCOUNT_USER_ID;
DELETE FROM  BANK_ACCOUNT WHERE USER_ID = NULL;

select * from ALL_CONSTRAINTS 
where constraint_name = 'FK_BANK_ACCOUNT_USER_ID';

SELECT * FROM BANK_ACCOUNT;


DROP TABLE BANK_ACCOUNT_USER_LOGON;


DELETE FROM USER_LOGIN WHERE USER_ID = 0;
DELETE FROM USER_LOGIN WHERE USER_NAME = "fuzzybear";

ALTER TABLE BANK_ACCOUNT
ADD CONSTRAINT FK_BANK_ACCOUNT_USER_ID
FOREIGN KEY(USER_ID) REFERENCES USER_LOGON(USER_ID);

/*ALTER TABLE USER_LOGON
ADD CONSTRAINT UQ_USERNAME UNIQUE(USERNAME);

ALTER TABLE USER_LOGON
ADD CONSTRAINT UQ_PASSWORD UNIQUE(PASSWORD);*/

SELECT * FROM USER_LOGON;
SELECT * FROM BANK_ACCOUNT;

/*ALTER TABLE BANK_ACCOUNT
DROP CONSTRAINT FK_BANK_ACCOUNT_USER_ID;*/

/*ALTER TABLE USER_LOGON
DROP CONSTRAINT UQ_USERNAME;

ALTER TABLE USER_LOGON
DROP CONSTRAINT UQ_PASSWORD;*/

TRUNCATE TABLE USER_LOGON;
TRUNCATE TABLE BANK_ACCOUNT;

CREATE SEQUENCE SQ_BANK_ACCOUNT_ID
START WITH 1
INCREMENT BY 1;

INSERT INTO BANK_ACCOUNT(BANK_ACCOUNT_ID)
VALUES (SQ_BANK_ACCOUNT_ID.NEXTVAL);

CREATE SEQUENCE SQ_USER_ID
START WITH 1
INCREMENT BY 1;

INSERT INTO USER_LOGON(USER_ID)
VALUES (SQ_USER_ID.NEXTVAL);
















