--------------------------------------------------------
--  File created - Monday-April-10-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANK_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "BANKMASTER"."BANK_ACCOUNT" 
   (	"BANK_ACCOUNTID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"BANK_ACCOUNT_NAME" VARCHAR2(160 BYTE), 
	"BALANCE" FLOAT(2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK_USER
--------------------------------------------------------

  CREATE TABLE "BANKMASTER"."BANK_USER" 
   (	"USER_ID" NUMBER(*,0), 
	"USER_NAME" VARCHAR2(120 BYTE), 
	"USER_PASSWORD" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SQ_USER_PK
--------------------------------------------------------

   CREATE SEQUENCE  "BANKMASTER"."SQ_USER_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into BANKMASTER.BANK_ACCOUNT
SET DEFINE OFF;
REM INSERTING into BANKMASTER.BANK_USER
SET DEFINE OFF;
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (32,'fifi','fafa');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (30,'fufu','nu');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (24,'luisnieves','1234');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (28,'bluedaba','dabadai');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (29,'hulu','netflix');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (31,'jiji','jaja');
Insert into BANKMASTER.BANK_USER (USER_ID,USER_NAME,USER_PASSWORD) values (33,'jesse','looped');
--------------------------------------------------------
--  DDL for Index PK_BANKACCID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANKMASTER"."PK_BANKACCID" ON "BANKMASTER"."BANK_ACCOUNT" ("BANK_ACCOUNTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "BANKMASTER"."PK_USERID" ON "BANKMASTER"."BANK_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TR_INSERT_USER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BANKMASTER"."TR_INSERT_USER" 
BEFORE INSERT ON BANK_USER
FOR EACH ROW
BEGIN 
    SELECT SQ_USER_PK.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/
ALTER TRIGGER "BANKMASTER"."TR_INSERT_USER" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_DEPOSIT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "BANKMASTER"."SP_DEPOSIT" (USE_ID IN NUMBER,DEPOSIT_AMT IN NUMBER)
IS
BEGIN
UPDATE BANK_ACCOUNT SET BALANCE = BALANCE + DEPOSIT_AMT WHERE USER_ID = USE_ID;
END;

/
--------------------------------------------------------
--  Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" ADD CONSTRAINT "PK_BANKACCID" PRIMARY KEY ("BANK_ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" MODIFY ("BALANCE" NOT NULL ENABLE);
  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" MODIFY ("BANK_ACCOUNT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" MODIFY ("BANK_ACCOUNTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK_USER
--------------------------------------------------------

  ALTER TABLE "BANKMASTER"."BANK_USER" ADD UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKMASTER"."BANK_USER" ADD CONSTRAINT "PK_USERID" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BANKMASTER"."BANK_USER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BANKMASTER"."BANK_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BANKMASTER"."BANK_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANK_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "BANKMASTER"."BANK_ACCOUNT" ADD CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "BANKMASTER"."BANK_USER" ("USER_ID") ENABLE;
